## Numpy Arrays

In [3]:
import numpy as np

In [11]:
array = np.array(range(5))

In [13]:
array

array([0, 1, 2, 3, 4])

In [15]:
array_2d = np.array([range(5), range(5)])

In [17]:
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [19]:
array_2d + 1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [21]:
array.shape

(5,)

In [23]:
array_2d.shape

(2, 5)

In [25]:
array.size

5

In [27]:
array_2d.size

10

In [29]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [31]:
array_2d.T.shape

(5, 2)

In [33]:
array.ndim

1

In [37]:
array_2d.ndim

2

In [39]:
array.dtype

dtype('int32')

In [41]:
array_2d.dtype

dtype('int32')

In [45]:
np.array(['I', 'love', 'Python'])

array(['I', 'love', 'Python'], dtype='<U6')

### Assignment 1

In [49]:
import numpy as np

In [51]:
my_list = [x * 10 for x in range(1, 11)]

In [55]:
my_list_array = np.array(my_list)

In [57]:
my_list_array.ndim

1

In [59]:
my_list_array.shape

(10,)

In [61]:
my_list_array.size

10

In [63]:
my_list_array.dtype

dtype('int32')

## Array Creation

In [68]:
np.ones(4,)

array([1., 1., 1., 1.])

In [70]:
np.ones(2, dtype='int')

array([1, 1])

In [72]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
np.zeros(100, 'int').reshape(10, 10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [78]:
np.zeros(100, 'int').reshape(5, 20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [80]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [86]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [94]:
np.zeros((5,20), 'int').T

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [96]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [106]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [152]:
#Evenly spaced intervals using linspace
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [122]:
np.linspace(8, 64, 8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [126]:
np.linspace(0, 64, 9)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64.])

In [148]:
np.arange(0, 73, 6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72])

## Random Number Array

In [158]:
import numpy as np

In [160]:
rng = np.random.default_rng(616)

In [162]:
rng.random(10)

array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [164]:
rng.integers(0, 10, 100)

array([8, 3, 6, 0, 3, 3, 1, 2, 2, 4, 9, 1, 2, 5, 1, 8, 9, 0, 3, 1, 5, 8,
       0, 6, 1, 7, 0, 7, 6, 0, 3, 7, 1, 9, 4, 1, 6, 1, 4, 4, 9, 5, 3, 4,
       7, 8, 3, 3, 5, 0, 4, 9, 9, 5, 6, 5, 8, 2, 3, 0, 0, 8, 3, 8, 4, 8,
       8, 9, 7, 3, 8, 4, 9, 2, 6, 3, 0, 3, 2, 0, 0, 4, 9, 5, 4, 1, 8, 2,
       7, 7, 1, 2, 2, 4, 1, 6, 7, 3, 7, 5], dtype=int64)

In [166]:
rng.normal(50, 5, 10)

array([53.53115044, 46.35468178, 46.1580894 , 52.89177118, 45.90693639,
       44.51748741, 57.41467712, 51.82624671, 53.9032125 , 53.21454641])

In [181]:
import numpy as np

rng = np.random.default_rng(12345)

random_ages = rng.integers(1, 101, 100)
random_ages

array([70, 23, 79, 32, 21, 80, 65, 68, 99, 40, 84, 34, 57, 60, 22, 19, 23,
       68, 62, 95, 71, 25, 92, 95, 74, 67, 14, 10, 27, 45,  8, 89, 48, 70,
       22, 33, 12, 74, 78, 23, 72,  9, 40, 16, 75, 35, 48, 47, 48, 27, 56,
       82, 50, 20,  3, 13,  9, 10, 13, 60, 81, 86, 66, 61, 34, 94, 65, 73,
       74, 87, 71, 93, 55, 55, 26, 94, 56, 50, 32, 28, 64, 46, 57, 67, 90,
       34, 69, 91, 46, 26, 30, 34, 63, 26, 84, 36,  7,  1,  3, 63],
      dtype=int64)

### Assignment 3

In [228]:
#1st problem
import numpy as np

array = np.linspace(10, 100, 10).reshape(5,2)
array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [230]:
array = np.arange(10, 101, 10).reshape(5,2)
array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [222]:
#2nd problem
from numpy.random import default_rng

In [224]:
rng = default_rng(2022)

In [226]:
rng.random(9).reshape(3, 3)

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

## Indexing and Slicing Arrays

In [234]:
import numpy as np

In [236]:
integer_array = np.arange(12)

In [238]:
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [242]:
integer_array[2]

2

In [244]:
integer_array[11]

11

In [246]:
integer_array[-1]

11

In [248]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [250]:
integer_array[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [252]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [254]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [257]:
new_array = integer_array.reshape(3,4)

new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [271]:
new_array[:, :]
#In slicing [], 1st argument is for ROWS, 2nd one is for COLUMNS.
#Based on giving params, you can slice the required portion from the array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [261]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [265]:
new_array[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [267]:
new_array[:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [269]:
new_array[2, 1]

9

### Demo

In [275]:
import numpy as np



In [277]:
ages = np.array([5, 10, 15, 19, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [281]:
youth_ages = ages[1:4]

youth_ages

array([10, 15, 19])

In [299]:
adult_ages = ages[4:-3]

adult_ages

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [297]:
senior_ages = ages[-3:]

senior_ages

array([70, 75, 80])

### Assignment 4

In [305]:
#2nd problem
from numpy.random import default_rng

rng = default_rng(2022)

random_array = rng.random(9).reshape(3, 3)

random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [319]:
random_array[0:2,:]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [317]:
random_array[:, 0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [315]:
random_array[2, 1]

0.04305584439252108

## Array Operations

In [323]:
import numpy as np

rng = np.random.default_rng(616)

inventory = rng.integers(0, 100, 10)

inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [325]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [327]:
(inventory / 2).dtype

dtype('float64')

In [335]:
price = (rng.random(10) * 10).round(2)

price

array([1.9 , 1.69, 4.74, 5.92, 4.25, 8.22, 3.8 , 0.22, 9.82, 5.5 ])

In [337]:
price * inventory

array([ 74.1 ,  65.91, 440.82, 509.12, 204.  , 378.12, 182.4 ,   6.6 ,
       108.02, 313.5 ])

In [343]:
inventory_list = list(inventory)

inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [347]:
inventory_list + 2

TypeError: can only concatenate list (not "int") to list

In [349]:
new_inventory = []

for x in inventory_list:
    new_inventory.append(x + 2)

new_inventory

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [351]:
[x + 2 for x in inventory_list]

[41, 41, 95, 88, 50, 48, 50, 32, 13, 59]

In [355]:
[x * y for x, y in zip(inventory_list, price)]

[74.1,
 65.91,
 440.82,
 509.12,
 204.0,
 378.12,
 182.39999999999998,
 6.6,
 108.02000000000001,
 313.5]

### Demo

In [361]:
import numpy as np

# Population age data for two small towns
town_a_ages = np.array([25, 45, 70, 34, 58])
town_b_ages = np.array([30, 55, 65, 40, 60])

age_differences = town_a_ages - town_b_ages 
age_differences

array([ -5, -10,   5,  -6,  -2])

### Assignment 5

In [365]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])


In [367]:
total = prices + 5

total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [407]:
from numpy.random import default_rng

rng = default_rng(2022)

random_array = rng.random(9).reshape(3, 3)

discount_pct = random_array[0:2, :].reshape(6)
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [415]:
pct_owed = 1 - discount_pct
pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [421]:
final_owed = (total * pct_owed).round(2)

final_owed

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])

## Filtering Arrays, Modifying Array Values

In [426]:
import numpy as np

In [430]:
my_array = np.arange(20)

my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [432]:
my_array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [434]:
my_array[my_array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [436]:
even_odd = np.array(['even', 'odd'] * 10)

even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [438]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [440]:
even_odd[even_odd != 'odd']

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

In [442]:
my_array[even_odd != 'odd'] = 0

In [444]:
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [446]:
my_array[2] = 2

In [448]:
my_array

array([ 0,  1,  2,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [451]:
mask = (even_odd != 'odd') | (even_odd != 'even')

even_odd[mask]

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [453]:
mask = (even_odd != 'odd') & (even_odd != 'even')

even_odd[mask]

array([], dtype='<U4')

## Where function

In [457]:
np.where(my_array % 2 == 0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [459]:
np.where(my_array % 2 == 0, 'even', np.where(my_array == 9, my_array, 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')

### Demo

In [468]:
import numpy as np

# Provided array of ages
ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])

adult_ages = np.where(ages > 18)

adult_ages

(array([0, 3, 4, 5, 6, 8, 9], dtype=int64),)

### Assignment 7

In [494]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [496]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [498]:
#1 Problem
selected_prooducts = products[prices > 25]

selected_prooducts

array(['rare tomato', 'gourmet ice cream'], dtype='<U17')

In [522]:
#2 Problem
fancy_feast_special = np.insert(selected_prooducts, 1, 'cola')

fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [524]:
#2 Problem 2nd solution
mask = (prices > 25) | (products == 'cola')

fancy_feast_special = products[mask]

fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [526]:
shipping_cost = np.where(prices > 20, 0, 5)

shipping_cost

array([5, 5, 0, 0, 5, 0])

## Array Aggregation

In [545]:
import numpy as np

In [547]:
rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [549]:
inventory = rng.integers(0, 100, 10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [551]:
price.mean()

5.6

In [553]:
inventory.mean()

35.3

In [555]:
inventory.sum()

353

In [557]:
inventory.max()

80

In [559]:
inventory.std()

20.48438429633656

In [563]:
(price * inventory).sum()

1848.2900000000002

In [565]:
(price * inventory).mean()

184.829

In [567]:
(price * inventory).max()

317.6

In [577]:
#argmax showing the index of most valuable product
(price * inventory).argmax()

0

In [575]:
#argmin showing the index of most valuable product
(price * inventory).argmin()

3

In [579]:
price_2d = price.reshape(5, 2)

In [581]:
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [585]:
price_2d.sum(axis=1) # row sum

array([12.63,  7.66,  6.63, 16.14, 12.94])

In [587]:
price_2d.sum(axis=0) # column sum

array([30.45, 25.55])

## Array Functions

In [591]:
import numpy as np

In [593]:
rng = np.random.default_rng(616)

price = (rng.random(10) * 10).round(2)

price

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [595]:
inventory = rng.integers(0, 100, 10)

inventory

array([80, 33, 60,  6, 31, 35, 16, 20, 29, 43], dtype=int64)

In [599]:
product_value = price * inventory
product_value

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [607]:
product_value.sort()
product_value

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [609]:
reshaped_product_value = product_value.reshape(2, 5)

reshaped_product_value

array([[ 18.36,  31.15, 141.12, 146.4 , 177.94],
       [212.28, 241.66, 276.  , 285.78, 317.6 ]])

In [611]:
np.median(reshaped_product_value)

195.11

In [613]:
np.percentile(reshaped_product_value, 50)

195.11

In [615]:
np.percentile(reshaped_product_value, 90)

288.962

In [617]:
np.percentile(reshaped_product_value, 10)

29.871000000000002

In [619]:
np.sqrt(reshaped_product_value)

array([[ 4.28485706,  5.5812185 , 11.87939392, 12.09958677, 13.33941528],
       [14.56983185, 15.54541733, 16.61324773, 16.90502884, 17.82133553]])

In [621]:
np.unique(reshaped_product_value)

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [623]:
np.unique(np.ones(100))

array([1.])

## Sorting Arrays

In [627]:
product_value = price * inventory
product_value

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [637]:
np.sort(product_value)

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [639]:
np.sort(product_value)[:5]

array([ 18.36,  31.15, 141.12, 146.4 , 177.94])

In [641]:
product_value.sort()

In [643]:
product_value

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [645]:
product_value[0]

18.36

In [647]:
product_value[-1]

317.6

In [649]:
product_value[::-1]

array([317.6 , 285.78, 276.  , 241.66, 212.28, 177.94, 146.4 , 141.12,
        31.15,  18.36])

### Assignment 8

In [654]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [656]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [660]:
#Task 1
sorted_prices = np.sort(prices)
sorted_prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [670]:
filtered_prices = sorted_prices[-3:]
filtered_prices

array([22.49, 49.99, 99.99])

In [678]:
print(np.mean(filtered_prices))
print(np.min(filtered_prices))
print(np.max(filtered_prices))
print(np.median(filtered_prices))

57.49
22.49
99.99
49.99


In [688]:
#Task 2
np.unique(price_tiers).size

3

## Vectorization Broadcasting

### Assignmet 9

In [694]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    r"D:\Self_Study\Udemy\Python\Python Data Analysis NumPy & Pandas Masterclass\Pandas+Course+Resources\Pandas Course Resources\retail\retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [696]:
family_array

array(['EGGS', 'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD', 'AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES',
       'BOOKS', 'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY',
       'DELI', 'EGGS', 'FROZEN FOODS', 'GROCERY I', 'GROCERY II',
       'HARDWARE', 'HOME AND KITCHEN I', 'HOME AND KITCHEN II',
       'HOME APPLIANCES', 'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN',
       'LINGERIE', 'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS',
       'PERSONAL CARE', 'PET SUPPLIES', 'PLAYERS AND ELECTRONICS',
       'POULTRY', 'PREPARED FOODS', 'PRODUCE',
       'SCHOOL AND OFFICE SUPPLIES', 'SEAFOOD', 'AUTOMOTIVE', 'BABY CARE',
       'BEAUT

In [712]:
sample = sales_array[family_array == 'PRODUCE']

sample

array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [714]:
sample.size

30

In [726]:
import numpy as np

rng = np.random.default_rng(2022)
random_array = rng.random(30)
random_array

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747, 0.98862926,
       0.96919869, 0.25697153, 0.55876211, 0.24234798, 0.32202029,
       0.89135975, 0.94611366, 0.72253931, 0.92847437, 0.99608701,
       0.2494223 , 0.06229007, 0.94479027, 0.65028587, 0.32167568,
       0.08336384, 0.21924361, 0.08417791, 0.05213927, 0.20525022])

In [728]:
produce_sample = sample[random_array < 0.5]

In [730]:
produce_sample

array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [734]:
mean = produce_sample.mean()
mean

2268.102470588235

In [738]:
median = np.median(produce_sample)

median

1272.755

In [740]:
np.where(produce_sample < median, 'below_both', np.where(produce_sample > mean, 'above_both', 'above_median'))

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')